export default {
  angleVariation: 1,
  scale: 0.9,
  angles: [
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard01.png',
      angle: 90,
      x: 0.334,
      y: 0.157,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard02.png',
      angle: 85,
      x: 0.232,
      y: 0.160,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard03.png',
      angle: 80,
      x: 0.223,
      y: 0.165,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard04.png',
      angle: 75,
      x: 0.209,
      y: 0.162,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard05.png',
      angle: 70,
      x: 0.203,
      y: 0.165,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard06.png',
      angle: 65,
      x: 0.194,
      y: 0.171,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard07.png',
      angle: 60,
      x: 0.185,
      y: 0.180,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard08.png',
      angle: 55,
      x: 0.177,
      y: 0.187,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard09.png',
      angle: 50,
      x: 0.167,
      y: 0.193,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard10.png',
      angle: 45,
      x: 0.161,
      y: 0.199,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard11.png',
      angle: 40,
      x: 0.150,
      y: 0.212,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard12.png',
      angle: 35,
      x: 0.146,
      y: 0.220,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard13.png',
      angle: 30,
      x: 0.138,
      y: 0.237,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard14.png',
      angle: 25,
      x: 0.130,
      y: 0.245,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard15.png',
      angle: 20,
      x: 0.130,
      y: 0.259,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard16.png',
      angle: 15,
      x: 0.128,
      y: 0.269,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard17.png',
      angle: 10,
      x: 0.126,
      y: 0.282,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard18.png',
      angle: 5,
      x: 0.122,
      y: 0.296,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard19.png',
      angle: 0,
      x: 0.136,
      y: 0.313,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard20.png',
      angle: -5,
      x: 0.121,
      y: 0.325,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard21.png',
      angle: -10,
      x: 0.121,
      y: 0.336,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard22.png',
      angle: -15,
      x: 0.125,
      y: 0.350,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard23.png',
      angle: -20,
      x: 0.131,
      y: 0.360,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard24.png',
      angle: -25,
      x: 0.135,
      y: 0.374,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard25.png',
      angle: -30,
      x: 0.140,
      y: 0.388,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard26.png',
      angle: -35,
      x: 0.147,
      y: 0.402,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard27.png',
      angle: -40,
      x: 0.148,
      y: 0.415,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard28.png',
      angle: -45,
      x: 0.159,
      y: 0.425,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard29.png',
      angle: -50,
      x: 0.162,
      y: 0.435,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard30.png',
      angle: -55,
      x: 0.168,
      y: 0.446,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard31.png',
      angle: -60,
      x: 0.177,
      y: 0.450,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard32.png',
      angle: -65,
      x: 0.186,
      y: 0.456,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard33.png',
      angle: -70,
      x: 0.195,
      y: 0.463,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard34.png',
      angle: -75,
      x: 0.209,
      y: 0.468,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard35.png',
      angle: -80,
      x: 0.215,
      y: 0.471,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard36.png',
      angle: -85,
      x: 0.225,
      y: 0.467,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_man_chalk_white/BrownManBlackboard37.png',
      angle: -90,
      x: 0.234,
      y: 0.463,
    },
  ],
  erasers: [
    {
      src: 'images/BrownMan_BlackboardEraser.png',
      x: 0.402,
      y: 0.064
    },
    {
      src: 'images/BrownMan_HandEraser.png',
      x: 0.343,
      y: 0.068
    },
  ]
}
