export default {
  angleVariation: 1,
  scale: 0.9,
  angles: [
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard01.png',
      angle: 90,
      x: 0.375,
      y: 0.078,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard02.png',
      angle: 85,
      x: 0.306,
      y: 0.081,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard03.png',
      angle: 80,
      x: 0.297,
      y: 0.082,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard04.png',
      angle: 75,
      x: 0.291,
      y: 0.084,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard05.png',
      angle: 70,
      x: 0.281,
      y: 0.085,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard06.png',
      angle: 65,
      x: 0.272,
      y: 0.092,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard07.png',
      angle: 60,
      x: 0.270,
      y: 0.093,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard08.png',
      angle: 55,
      x: 0.264,
      y: 0.099,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard09.png',
      angle: 50,
      x: 0.256,
      y: 0.105,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard10.png',
      angle: 45,
      x: 0.249,
      y: 0.111,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard11.png',
      angle: 40,
      x: 0.244,
      y: 0.125,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard12.png',
      angle: 35,
      x: 0.239,
      y: 0.131,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard13.png',
      angle: 30,
      x: 0.237,
      y: 0.137,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard14.png',
      angle: 25,
      x: 0.231,
      y: 0.150,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard15.png',
      angle: 20,
      x: 0.227,
      y: 0.161,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard16.png',
      angle: 15,
      x: 0.223,
      y: 0.171,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard17.png',
      angle: 10,
      x: 0.221,
      y: 0.180,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard18.png',
      angle: 5,
      x: 0.219,
      y: 0.194,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard19.png',
      angle: 0,
      x: 0.216,
      y: 0.210,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard20.png',
      angle: -5,
      x: 0.216,
      y: 0.220,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard21.png',
      angle: -10,
      x: 0.216,
      y: 0.227,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard22.png',
      angle: -15,
      x: 0.217,
      y: 0.240,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard23.png',
      angle: -20,
      x: 0.220,
      y: 0.251,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard24.png',
      angle: -25,
      x: 0.223,
      y: 0.265,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard25.png',
      angle: -30,
      x: 0.224,
      y: 0.274,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard26.png',
      angle: -35,
      x: 0.228,
      y: 0.284,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard27.png',
      angle: -40,
      x: 0.233,
      y: 0.289,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard28.png',
      angle: -45,
      x: 0.237,
      y: 0.300,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard29.png',
      angle: -50,
      x: 0.241,
      y: 0.308,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard30.png',
      angle: -55,
      x: 0.250,
      y: 0.318,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard31.png',
      angle: -60,
      x: 0.257,
      y: 0.324,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard32.png',
      angle: -65,
      x: 0.266,
      y: 0.328,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard33.png',
      angle: -70,
      x: 0.270,
      y: 0.334,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard34.png',
      angle: -75,
      x: 0.279,
      y: 0.338,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard35.png',
      angle: -80,
      x: 0.286,
      y: 0.338,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard36.png',
      angle: -85,
      x: 0.292,
      y: 0.341,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/brown_woman_chalk_white/BrownWomanBlackboard37.png',
      angle: -90,
      x: 0.300,
      y: 0.345,
    },
  ],
  erasers: []
}
