export default {
  angleVariation: 0.85,
  angles: [
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H01.png',
      angle: 90,
      x: 0.33,
      y: 0.168,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H02.png',
      angle: 85,
      x: 0.319,
      y: 0.168,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H03.png',
      angle: 80,
      x: 0.316,
      y: 0.170,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H04.png',
      angle: 75,
      x: 0.310,
      y: 0.173,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H05.png',
      angle: 70,
      x: 0.303,
      y: 0.175,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H06.png',
      angle: 65,
      x: 0.295,
      y: 0.177,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H07.png',
      angle: 60,
      x: 0.291,
      y: 0.178,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H08.png',
      angle: 55,
      x: 0.282,
      y: 0.184,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H09.png',
      angle: 50,
      x: 0.277,
      y: 0.191,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H10.png',
      angle: 45,
      x: 0.270,
      y: 0.195,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H11.png',
      angle: 40,
      x: 0.266,
      y: 0.200,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H12.png',
      angle: 35,
      x: 0.261,
      y: 0.208,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H13.png',
      angle: 30,
      x: 0.254,
      y: 0.212,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H14.png',
      angle: 25,
      x: 0.251,
      y: 0.225,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H15.png',
      angle: 20,
      x: 0.246,
      y: 0.236,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H16.png',
      angle: 15,
      x: 0.245,
      y: 0.244,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H17.png',
      angle: 10,
      x: 0.244,
      y: 0.252,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H18.png',
      angle: 5,
      x: 0.240,
      y: 0.262,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H19.png',
      angle: 0,
      x: 0.242,
      y: 0.273,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H20.png',
      angle: -5,
      x: 0.240,
      y: 0.282,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H21.png',
      angle: -10,
      x: 0.242,
      y: 0.287,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H22.png',
      angle: -15,
      x: 0.243,
      y: 0.302,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H23.png',
      angle: -20,
      x: 0.244,
      y: 0.307,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H24.png',
      angle: -25,
      x: 0.246,
      y: 0.316,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H25.png',
      angle: -30,
      x: 0.250,
      y: 0.325,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H26.png',
      angle: -35,
      x: 0.254,
      y: 0.335,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H27.png',
      angle: -40,
      x: 0.256,
      y: 0.341,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H28.png',
      angle: -45,
      x: 0.261,
      y: 0.346,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H29.png',
      angle: -50,
      x: 0.265,
      y: 0.356,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H30.png',
      angle: -55,
      x: 0.274,
      y: 0.366,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H31.png',
      angle: -60,
      x: 0.276,
      y: 0.362,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H32.png',
      angle: -65,
      x: 0.282,
      y: 0.369,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H33.png',
      angle: -70,
      x: 0.289,
      y: 0.375,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H34.png',
      angle: -75,
      x: 0.298,
      y: 0.377,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H35.png',
      angle: -80,
      x: 0.302,
      y: 0.387,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H36.png',
      angle: -85,
      x: 0.314,
      y: 0.392,
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/H37.png',
      angle: -90,
      x: 0.317,
      y: 0.390,
    },
  ],
  erasers: [
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/WhiteMan_eraser_blackboard-2.png',
      x: 0.452,
      y: 0.061
    },
    {
      src: 'https://d207npbduzzt0t.cloudfront.net/hands/blackboard/no_clothes_chalk_white/WhiteMan_HandEraser.png',
      x: 0.422,
      y: 0.038
    },
  ]
}
